# This file can only be edited inside the uBlue image's git repository.

# The image will be at "ghcr.io/yourusername/name".
name: lunatic-ublue
base-image: ghcr.io/ublue-os/kinoite-nvidia
fedora-version: 39
description: Custom image based on uBlue Kinoite Nvidia

scripts:
  pre:
    - autorun.sh
  post:
    - nvidia-kargs.sh

rpm:
  repos:

  install:
    - python3-pip
    - libadwaita
    - qemu
    - VirtualBox
    - kalendar
  remove:
    - firefox
    - firefox-langpacks

firstboot:
  yafti: true

  flatpaks:
    - org.mozilla.firefox
    - org.kde.krita
    - com.brave.Browser
    - com.valvesoftware.Steam
    - io.github.vinegarhq.Vinegar
    - org.blender.Blender
    - org.gimp.GIMP
    - org.inkscape.Inkscape
    - net.lutris.Lutris
    - io.github.shiftey.Desktop
    - com.discordapp.Discord
    - com.obsproject.Studio
    - md.obsidian.Obsidian
    - net.davidotek.pupgui
    - org.mozilla.Thunderbird
    - com.spotify.Client
    - org.libreoffice.LibreOffice
    - org.onlyoffice.desktopeditors
    - org.audacityteam.Audacity
    - org.kde.kdenlive
    - org.telegram.desktop
    - org.kde.neochat
    - org.prismlauncher.PrismLauncher
